import './css/styles.scss';
import './components/mainPage/mainPage';
import './components/ItemModal/ItemModal';
import './components/navigationMenu/navigationMenu';
import './services/api';
import './components/header/header';
import './components/authentication/authServises';
import './components/AuthForm/authOpenModal';
import './components/AuthForm/authOpenModal';
